# Generated by Django 4.0.3 on 2022-04-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.department'),
        ),
    ]
