# Generated by Django 4.0.3 on 2022-04-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0002_customuser_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='status_description',
        ),
        migrations.AlterField(
            model_name='employees',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_information.department'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_information.position'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_information.statusemployee'),
        ),
    ]
