# Generated by Django 4.0.3 on 2022-04-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0003_remove_employees_status_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_information.department'),
        ),
    ]
