# Generated by Django 4.0.3 on 2022-04-24 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0004_alter_customuser_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='code',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_information.department', verbose_name='Название подразделения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_hr',
            field=models.BooleanField(default=False, help_text='Указывает, кадровик ли сотрудник.', verbose_name='Кадровик'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_mainHR',
            field=models.BooleanField(default=False, help_text='Указывает, кадровик центрального аппарата ли сотрудник.', verbose_name='Кадровик центрального аппарата'),
        ),
    ]
