# Generated by Django 4.0.3 on 2022-05-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_remove_employees_code_alter_customuser_department_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='IIN',
        ),
    ]
