# Generated by Django 4.0.3 on 2022-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0007_department_sort_id_position_sort_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='fullname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
