# Generated by Django 4.0.3 on 2022-10-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0008_employees_fullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
